# https://eslint.org/docs/user-guide/configuring
root: true
parser: babel-eslint

env:
  node: true
  browser: true
  es6: true
  commonjs: true

rules:
  strict: off
  semi: off
  indent:
    - error
    - 2
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-alert: error
  no-undef: error
  no-empty: error
  no-var: error
  no-mixed-spaces-and-tabs: 2
globals:
  TimelineLite: false
  TimelineMax: false
  TweenLite: false
  TweenMax: false
  Back: false
  Bounce: false
  Circ: false
  Cubic: false
  Ease: false
  EaseLookup: false
  Elastic: false
  Expo: false
  Linear: false
  Power0: false
  Power1: false
  Power2: false
  Power3: false
  Power4: false
  Quad: false
  Quart: false
  Quint: false
  RoughEase: false
  Sine: false
  SlowMo: false
  SteppedEase: false
  Strong: false
  Draggable: false
  SplitText: false
  VelocityTracker: false
  CSSPlugin: false
  ThrowPropsPlugin: false
  BezierPlugin: false
  PIXI: false
  moment: false
